packages:
  - "apps/*"
  - "packages/*"

catalog:
  '@eslint/js': ^9.39.1
  '@nestjs/bullmq': ^11.0.4
  '@nestjs/common': ^11.1.9
  '@nestjs/core': ^11.1.9
  '@nestjs/platform-express': ^11.1.9
  '@nestjs/swagger': ^11.2.3
  '@nestjs/testing': ^11.1.9
  '@prisma/client': ^6.19.0
  '@types/node': ^24.10.1
  bullmq: ^5.66.0
  eslint: ^9.39.1
  node-vibrant: ^4.0.3
  pino: ^10.1.0
  pino-pretty: ^13.1.2
  prisma: ^6.19.0
  reflect-metadata: ^0.2.2
  rxjs: ^7.8.2
  tesseract.js: ^6.0.1
  tsx: ^4.21.0
  turbo: ^2.6.1
  typescript: ^5.9.3
  typescript-eslint: ^8.46.4
  vite: ^8.0.12
  vitest: ^4.0.15
  zod: ^4.1.13

allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
